version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbPassword
      MYSQL_DATABASE: social_network
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: dbPassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: social_network_backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/social_network
      SPRING_DATASOURCE_USERNAME: dbUser
      SPRING_DATASOURCE_PASSWORD: dbPassword


  frontend:
    build: ./front-end
    container_name: social_network_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

  flask_ai:
    build: ./ml
    container_name: flask_ai
    restart: always
    depends_on:
      - mysql
    ports:
      - "5001:5001"
    environment:
      FLASK_RUN_HOST: 0.0.0.0
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
